name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    # Run all steps in the same container so that the Azure CLI login context persists
    container:
      image: node:20-bullseye
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash

      - name: Install Azure SWA CLI
        run: |
          npm install -g @azure/static-web-apps-cli

      - name: (Optional) Install Azure Static Web Apps CLI extension
        run: |
          # Uncomment the next line if the "az staticwebapp" commands are not available:
          # az extension add --name azure-swa
          echo "Azure Static Web Apps extension (if needed) installed."

      - name: Azure Login
        run: |
          az login --service-principal \
            --username "${{ secrets.AZURE_CLIENT_ID }}" \
            --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
            --tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Add GitHub Runner IP to Key Vault Firewall
        run: |
          echo "Fetching public IP of the GitHub runner..."
          runner_ip=$(curl -s https://api.ipify.org)
          echo "Runner IP: $runner_ip"
          # Extract the key vault name from the KEY_VAULT_URL secret.
          # Assumes the format: https://<keyvault-name>.vault.azure.net
          keyvault_name="notsosecretkv"
          echo "Adding IP $runner_ip to Key Vault '$keyvault_name' firewall..."
          az keyvault network-rule add --name "$keyvault_name" --ip-address "$runner_ip"

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        env:
          KEY_VAULT_URL: ${{ secrets.KEY_VAULT_URL }}
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        run: |
          swa deploy ./out -d ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_MEADOW_0F305680F }} -n wa-kvwebapptest --env production
