# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - wa-kvwebapptest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20-bullseye

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Add GitHub Runner IP to Key Vault Firewall
        run: |
          echo "Fetching public IP of the GitHub runner..."
          runner_ip=$(curl -s https://api.ipify.org)
          echo "Runner IP: $runner_ip"
          # Extract the key vault name from the KEY_VAULT_URL secret.
          # Assumes the format: https://<keyvault-name>.vault.azure.net
          keyvault_name="notsosecretkv"
          echo "Adding IP $runner_ip to Key Vault '$keyvault_name' firewall..."
          az keyvault network-rule add --name "$keyvault_name" --ip-address "$runner_ip"

      - name: npm install, build, and test
        env:
          KEY_VAULT_URL: ${{ secrets.KEY_VAULT_URL }}
        run: |
          npm install
          npm run build
          mv ./build/static ./build/standalone/build
          mv ./public ./build/standalone
#          npm run test --if-present

      - name: Zip for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip the artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'wa-kvwebapptest'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A48C70623F574A8FB3F39682FF9E607D }}
          package: ./build/standalone
